-- 먼저 PRODUCT_ID 각 행에 대한 가격과, 판매량 구하기 
-- PRODUCT_ID, 가격*판매량 
-- 마지막 결과를 GROUP BY하고 정렬

SELECT PRODUCT_CODE, SUM(PRICE*SALES_AMOUNT) AS SALES
    FROM PRODUCT JOIN OFFLINE_SALE
    USING (PRODUCT_ID)
    GROUP BY 1
    ORDER BY 2 DESC, 1;