-- 코드를 입력하세요
SELECT P.PRODUCT_ID, P.PRODUCT_NAME, SUM(P.PRICE*O.AMOUNT) AS TOTAL_SALES
    FROM FOOD_PRODUCT AS P INNER JOIN FOOD_ORDER AS O
    ON P.PRODUCT_ID = O.PRODUCT_ID
    WHERE MONTH(O.PRODUCE_DATE) = 5
    GROUP BY 1
    ORDER BY 3 DESC, 1;