-- 코드를 입력하세요
SELECT A.FLAVOR
FROM FIRST_HALF A INNER JOIN JULY B
ON A.FLAVOR = B.FLAVOR
GROUP BY A.FLAVOR
HAVING SUM(A.TOTAL_ORDER + B.TOTAL_ORDER)
ORDER BY SUM(A.TOTAL_ORDER + B.TOTAL_ORDER) DESC 
LIMIT 3;