-- 코드를 입력하세요
SELECT A.FLAVOR
    FROM FIRST_HALF AS A
    INNER JOIN (SELECT FLAVOR, SUM(TOTAL_ORDER) AS J_TOTAL 
                FROM JULY
                GROUP BY FLAVOR) B
    ON A.FLAVOR = B.FLAVOR
    ORDER BY A.TOTAL_ORDER + B.J_TOTAL DESC
    LIMIT 3;
