-- 코드를 입력하세요
SELECT B.USER_ID, B.NICKNAME, SUM(A.PRICE) AS TOTAL_SALES
    FROM USED_GOODS_BOARD AS A INNER JOIN USED_GOODS_USER AS B
    ON A.WRITER_ID = B.USER_ID
    WHERE STATUS = 'DONE'
    GROUP BY 1,2
    HAVING TOTAL_SALES >= 700000
    ORDER BY 3;